name: Customize Repo
on: 
  workflow_dispatch:
    inputs:
      language:
        description: 'Language (Python or R)'     
        required: true
        default: 'Python'
      category:
        description: 'Project Type (Type A, Type B, Type C)'
        required: true
        default: 'Type A'

jobs:
  customize-repo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.language }}"
        echo "Tags: ${{ github.event.inputs.category }}" 
    
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        path: primary

    - name: Checkout customization repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_ORG_TOKEN }}
        repository: ${{ github.repository_owner }}/${{ github.event.inputs.language }}
        path: ${{ github.event.inputs.language }}
    - name: Make customization changes to repo
      run: |
        rm -rf ./$CUST_REPO/.git
        cp -r ./$CUST_REPO/. ./primary
        echo "### New Repo" > ./primary/README.md
        echo "This is a ${CATEGORY} repo!" >> ./primary/README.md
        echo "" >> ./primary/README.md
        echo "#### Description" >> ./primary/README.md
        echo "<!-- Add a description here -->" >> ./primary/README.md
      env:
        CUST_REPO: ${{ github.event.inputs.language }}
        CATEGORY: ${{ github.event.inputs.category }}

    - name: Cleanup Repo Customization Action
      run: |
            cd ./primary
            rm ./.github/workflows/customize-repo.yml
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        directory: primary
